app_home:
    path: /
    controller: App\Controller\HomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_bicycle_index:
    path: /bikes
    controller: App\Controller\BicycleController::index

app_bicycle_new:
    path: /new-bike
    controller: App\Controller\BicycleController::new

app_bicycle_show:
    path: /bike/{id}/show
    controller: App\Controller\BicycleController::show

app_bicycle_edit:
    path: /bike/{id}/edit
    controller: App\Controller\BicycleController::edit

app_bicycle_delete:
    path: /bike/{id}/delete
    controller: App\Controller\BicycleController::delete